name: Java CI with Maven

on:
  push:
    branches:
    - develop
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/ci.yaml
  pull_request_target:
    branches:
    - develop
    - main
    paths:
    - src/**
    - pom.xml
    - .github/workflows/ci.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Import Secrets
      id: secrets
      uses: hashicorp/vault-action@v2.5.0
      with:
        exportToken: true
        exportEnv: true
        method: jwt
        url: ${{ secrets.VAULT_ADDR }}
        role: cicd
        secrets: |
          kv/data/cicd/sonatype username | SONATYPE_USERNAME ;
          kv/data/cicd/sonatype password | SONATYPE_PASSWORD ;
          kv/data/cicd/gpg secring | GPG_SECRING ;
          kv/data/cicd/gpg passphrase | GPG_PASSPHRASE ;
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'liberica'
        cache: maven
        gpg-private-key: ${{ steps.secrets.outputs.GPG_SECRING }}
        gpg-passphrase: ${{ steps.secrets.outputs.GPG_PASSPHRASE }}
    - name: Unit Tests
      run: ./mvnw -V --no-transfer-progress clean test
    - name: Deploy to sonatype-snapshots
      if: github.ref == 'refs/heads/develop'
      run: |
        set -e
        cat > settings.xml <<EOF
        <settings>
          <servers>
            <server>
               <id>sonatype-snapshots</id>
               <username>${SONATYPE_USERNAME}</username>
               <password>${SONATYPE_PASSWORD}</password>
            </server>
          </servers>
        </settings>
        EOF
        CURRENT_VERSION=$(grep '<version>' pom.xml | head -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's| ||g' |  tr -d '\t')
        if [ "${CURRENT_VERSION}" = "$(echo ${CURRENT_VERSION} | grep "\-SNAPSHOT")" ];then
          ./mvnw -V deploy -s settings.xml --no-transfer-progress -DskipTests=true -DserverId=sonatype-snapshots
        fi
    - name: Deploy to sonatype-releases
      if: github.ref == 'refs/heads/main'
      run: |
        set -e
        cat > settings.xml <<EOF
        <settings>
          <servers>
            <server>
               <id>repo</id>
               <username>${SONATYPE_USERNAME}</username>
               <password>${SONATYPE_PASSWORD}</password>
            </server>
          </servers>
        </settings>
        EOF
        mvn -V \
            javadoc:jar \
            source:jar \
            package \
            org.apache.maven.plugins:maven-gpg-plugin:3.0.1:sign \
            org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:deploy \
            --no-transfer-progress \
            -s settings.xml \
            -DserverId=repo \
            -Dgpg.passphrase=${GPG_PASSPHRASE} \
            -DnexusUrl=https://oss.sonatype.org \
            -DautoReleaseAfterClose=true \
            -DaltDeploymentRepository=repo::default::https://oss.sonatype.org/service/local/staging/deploy/maven2 \
            -DskipTests=true
    - name: Revoke token
      if: always()
      run: |
        curl -X POST -s -H "X-Vault-Token: ${VAULT_TOKEN}" ${{ secrets.VAULT_ADDR }}/v1/auth/token/revoke-self
